### ISSUE TITLE
Demonstration: Configuring Azure Resource Manager Windows virtual machines with DSC script fails

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#126] opened 2017-04-03 15:29 UTC
Hi, problem with module 4.
First Demo: Setup-Azure takes 0 seconds and doesn't ask for an Azure logon.
After completing the "Configuring Azure VM availability sets" demonstraton as in the March 2017 slide notes, the "D:\Demofiles\Mod04\DeployAzureDSC.ps1" script fails.
I have 12K plus lines of error before crtl C stops the script. I get the same error in Pass Azure and MSDN subscriptions. Here are the first few lines of error:
Get-AzureRmStorageAccountNameAvailability : Run Login-AzureRmAccount to login.
At D:\Demofiles\Mod04\DeployAzureDSC.ps1:13 char:8
+ $try = Get-AzureRmStorageAccountNameAvailability -Name $saName
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmStor...ameAvailability], PSInvali 
   dOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Management.Storage.Storag 
   eAccount.GetAzureStorageAccountNameAvailability
 
Get-AzureRmStorageAccountNameAvailability : Run Login-AzureRmAccount to login.
At D:\Demofiles\Mod04\DeployAzureDSC.ps1:18 char:10
+ ...        $try = Get-AzureRmStorageAccountNameAvailability -Name $saName
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmStor...ameAvailability], PSInvali 
   dOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Management.Storage.Storag 
   eAccount.GetAzureStorageAccountNameAvailability
 
Get-AzureRmStorageAccountNameAvailability : Run Login-AzureRmAccount to login.
At D:\Demofiles\Mod04\DeployAzureDSC.ps1:18 char:10
+ ...        $try = Get-AzureRmStorageAccountNameAvailability -Name $saName
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by polichtm** [comment] 2017-04-03 15:40
Hi Karine - pls download the updated Setup-Azure module, restart the lab VM, and give it another try
thnx
Marcin

**Comment by KarineMerritt** [comment] 2017-04-04 10:24
@polichtm 
I have downloaded all the latest Allfiles and rebooted MIA-CL1. I have run the new setup-azure (Mod4)
**Here are the results of running DeployAzureDSC.ps1 line by line:**
PS C:\Windows\system32> Login-AzureRmAccount
Environment           : AzureCloud
Account               : karine.merritt@outlook.com
TenantId              : b667d16c-a352-4de4-9075-18c9aafef1a5
SubscriptionId        : 5125ad8a-8a69-40f4-9394-6def8291d32b
SubscriptionName      : MSDN Platforms
CurrentStorageAccount : 

PS C:\Windows\system32> Show-SubscriptionARM
[1] -  MSDN Platforms - Id:  5125ad8a-8a69-40f4-9394-6def8291d32b
[2] -  Pass Azure - Id:  9d5aa416-101c-4295-b9d3-aed69c7e3d8b

Select the Azure subscription: 1
Using subscription:  MSDN Platforms  Id:  5125ad8a-8a69-40f4-9394-6def8291d32b  (Resource Manager)

Environment           : AzureCloud
Account               : karine.merritt@outlook.com
TenantId              : b667d16c-a352-4de4-9075-18c9aafef1a5
SubscriptionId        : 5125ad8a-8a69-40f4-9394-6def8291d32b
SubscriptionName      : MSDN Platforms
CurrentStorageAccount : 

PS C:\Windows\system32> $resourceGroupName = '20533C0401-LabRG'

PS C:\Windows\system32> _```
$storageAccount = Get-AzureRmStorageAccount -ResourceGroupName $resourceGroupName
Get-AzureRmStorageAccount : Run Login-AzureRmAccount to login.
At line:1 char:19
+ ... geAccount = Get-AzureRmStorageAccount -ResourceGroupName $resourceGro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmStorageAccount], PSInvalidOperati 
   onException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Management.Storage.GetAzu 
   reStorageAccountCommand
```_

Here are all my resources:
20533c0401labrgdisks859  Storage account 20533c0401-labrg UK South MSDN Platforms  
20533c0401-labrg-vnet  Virtual network 20533c0401-labrg UK South MSDN Platforms  
resdevwebas  Availability set 20533c0401-labrg UK South MSDN Platforms  
resdevweblb  Load balancer 20533c0401-labrg UK South MSDN Platforms  
resdevweblb-ip  Public IP address 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm1  Virtual machine 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm1929  Network interface 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm1-ip  Public IP address 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm1-nsg  Network security group 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm2  Virtual machine 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm262  Network interface 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm2-ip  Public IP address 20533c0401-labrg UK South MSDN Platforms  
resdevwebvm2-nsg  Network security group 20533c0401-labrg UK South MSDN Platforms

**Comment by polichtm** [comment] 2017-04-04 19:51
make sure to use non-managed disks for the demos and labs in this module. We'll be updating scripts to account for any potential confusion

**Comment by polichtm** [comment] 2017-04-05 15:42
this is a duplicate of the other issue which is being addressed

**Closed by polichtm** 2017-04-05 15:42 UTC
