### ISSUE TITLE
Changes to the Azure Portal

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#288] opened 2018-02-23 22:25 UTC
The Azure Portal has the following changes:
1."+New" button is now "+Create a resource" button
2."More Services" button at the bottom of the menu is now "All Services" at the top

Instructions will need to be updated accordingly.

**Comment by itbland** [comment] 2018-02-23 22:39
Duplicate of #287 
@polichtm merged those changes last Tuesday, the code should be good for those two changes.

**Closed** 2018-02-24 00:15 UTC
